version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./locales:/app/locales
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis_data: