name: Auto Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ubuntu/expanse-telegram-bot
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart expanse-bot
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sleep 5
          if systemctl is-active --quiet expanse-bot; then
            echo "✅ Bot is running"
          else
            echo "❌ Bot failed to start"
            exit 1
          fi